// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeListSync.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20231011114904_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Association", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Associations");
                });

            modelBuilder.Entity("SeriesAssociation", b =>
                {
                    b.Property<long>("AnimeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AssociationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimeId", "AssociationId");

                    b.ToTable("SeriesAssociations");
                });

            modelBuilder.Entity("SeriesBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.ToTable("Series");

                    b.HasDiscriminator<int>("Provider");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MalSeries", b =>
                {
                    b.HasBaseType("SeriesBase");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("ShindenSeries", b =>
                {
                    b.HasBaseType("SeriesBase");

                    b.HasDiscriminator().HasValue(1);
                });
#pragma warning restore 612, 618
        }
    }
}
