// <auto-generated />
using AnimeListSync.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeListSync.DB.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("AnimeListSync.DB.Entity.InternalSeries", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InternalSeriesSet");
                });

            modelBuilder.Entity("AnimeListSync.DB.Entity.ProviderEntity", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProviderSet");

                    b.HasData(
                        new
                        {
                            Id = (byte)0,
                            Description = "MyAnimeList (https://myanimelist.net)",
                            Name = "MyAnimeList"
                        },
                        new
                        {
                            Id = (byte)1,
                            Description = "Shinden (https://shinden.pl)",
                            Name = "Shinden"
                        });
                });

            modelBuilder.Entity("AnimeListSync.DB.Entity.ProviderSeries", b =>
                {
                    b.Property<byte>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdFromProvider")
                        .HasColumnType("TEXT");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InternalSeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProviderId", "IdFromProvider");

                    b.HasIndex("InternalSeriesId");

                    b.ToTable("ProviderSeriesSet");
                });

            modelBuilder.Entity("AnimeListSync.DB.Entity.ProviderSeries", b =>
                {
                    b.HasOne("AnimeListSync.DB.Entity.InternalSeries", "InternalSeries")
                        .WithMany()
                        .HasForeignKey("InternalSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeListSync.DB.Entity.ProviderEntity", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InternalSeries");

                    b.Navigation("Provider");
                });
#pragma warning restore 612, 618
        }
    }
}
